steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/taps-analytics-ui-proxy:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/taps-analytics-ui-proxy:latest'
      - '.'
    timeout: '300s'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/taps-analytics-ui-proxy:$SHORT_SHA']
    timeout: '300s'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/taps-analytics-ui-proxy:latest']
    timeout: '300s'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'taps-analytics-ui-proxy'
      - '--image'
      - 'gcr.io/$PROJECT_ID/taps-analytics-ui-proxy:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--max-instances=10'
      - '--timeout=300'
      - '--set-env-vars'
      - 'BACKEND_URL=${_BACKEND_URL}'
    timeout: '300s'

substitutions:
  _BACKEND_URL: 'https://YOUR-NEW-SERVICE-URL.run.app'

options:
  machineType: 'E2_HIGHCPU_4'
  logging: CLOUD_LOGGING_ONLY

