steps:
  # Run targeted tests before building (quality gate)
  - name: 'python:3.11'
    id: 'pre-test'
    entrypoint: bash
    args:
      - -lc
      - |
        pip install -q -r requirements.txt pytest && \
        pytest -q tests/test_ui_deployment.py

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/taps-analytics-ui', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/taps-analytics-ui']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'taps-analytics-ui'
      - '--image'
      - 'gcr.io/$PROJECT_ID/taps-analytics-ui'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--concurrency'
      - '80'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'API_BASE_URL='
      - '--set-env-vars'
      - 'DATABASE_TERMINAL_URL=https://your-sqlpad-instance.run.app'
      - '--set-env-vars'
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID'
      - '--set-env-vars'
      - 'GCP_REGION=us-central1'

images:
  - 'gcr.io/$PROJECT_ID/taps-analytics-ui'



