steps:
  # Step 1: Build container using pre-built base image (ultra-fast)
  # Base image contains all dependencies, so this only copies code
  # Use COMMIT_SHA from GitHub trigger, or SHORT_SHA from manual trigger
  - name: 'gcr.io/cloud-builders/docker'
    env:
      - 'DOCKER_BUILDKIT=1'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/taps-analytics-ui:${SHORT_SHA}'
      - '--build-arg'
      - 'BASE_IMAGE=gcr.io/$PROJECT_ID/taps-analytics-ui-base:latest'
      - '--cache-from'
      - 'gcr.io/$PROJECT_ID/taps-analytics-ui:latest'
      - '--cache-from'
      - 'gcr.io/$PROJECT_ID/taps-analytics-ui-base:latest'
      - '--build-arg'
      - 'BUILDKIT_INLINE_CACHE=1'
      - '.'
    timeout: '120s'

  # Step 2: Push image (only SHA tag - skip latest to save time)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/taps-analytics-ui:${SHORT_SHA}']
    timeout: '300s'

  # Step 3: Deploy to Cloud Run (can start while image is being pushed)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'taps-analytics-ui'
      - '--image'
      - 'gcr.io/$PROJECT_ID/taps-analytics-ui:${SHORT_SHA}'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--set-secrets'
      - 'GOOGLE_AI_API_KEY=google-ai-api-key:latest'
      - '--quiet'
    timeout: '300s'


# Define images for caching (only SHA tag - latest removed for speed)
images:
  - 'gcr.io/$PROJECT_ID/taps-analytics-ui:${SHORT_SHA}'

# Optimize for speed
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  diskSizeGb: 100
  # Enable BuildKit for cache mounts
  env:
    - 'DOCKER_BUILDKIT=1'
  # Use Cloud Build's built-in caching
  substitution_option: 'ALLOW_LOOSE'

# Substitutions for GitHub triggers
# SHORT_SHA will be set automatically from COMMIT_SHA by the trigger
substitutions:
  SHORT_SHA: '${COMMIT_SHA:0:7}'  # First 7 chars of commit SHA