steps:
  # Step 1: Build container and push to Artifact Registry with caching
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/taps-analytics-ui:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/taps-analytics-ui:latest'
      - '--cache-from'
      - 'gcr.io/$PROJECT_ID/taps-analytics-ui:latest'
      - '.'
    timeout: '600s'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/taps-analytics-ui:$SHORT_SHA']
    timeout: '600s'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/taps-analytics-ui:latest']
    timeout: '600s'

  # Step 2: Deploy new image to Cloud Run with traffic swap
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'taps-analytics-ui'
      - '--image'
      - 'gcr.io/$PROJECT_ID/taps-analytics-ui:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
    timeout: '600s'

  # Step 3: Set IAM policy for public access
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'services'
      - 'add-iam-policy-binding'
      - 'taps-analytics-ui'
      - '--region'
      - 'us-central1'
      - '--member'
      - 'allUsers'
      - '--role'
      - 'roles/run.invoker'
    timeout: '300s'

# Define images for caching
images:
  - 'gcr.io/$PROJECT_ID/taps-analytics-ui:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/taps-analytics-ui:latest'

# Optimize for speed
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  diskSizeGb: 100

# Substitution variables for secrets
substitutions:
  _GEMINI_API_KEY: ''
  _GEMINI_BASE_URL: ''