name: Deploy to Cloud Run

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: taps-data
  REGION: us-central1

jobs:
  deploy-staging:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build and Deploy to Staging
      run: |
        gcloud builds submit --config cloudbuild-staging.yaml \
          --substitutions=_GEMINI_API_KEY="${{ secrets.GEMINI_API_KEY }}"

  deploy-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build and Deploy to Production
      run: |
        gcloud builds submit --config cloudbuild.yaml \
          --substitutions=_GEMINI_API_KEY="${{ secrets.GEMINI_API_KEY }}"
